name: Sample Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Saying Hello World
        run: echo "Sup Dude!"
      - name: Saying Goodbye
        run: echo "Pease nerds!!"
